---
- name: Instalar Httpd
  yum:
    name: httpd
    state: present

- name: Copiar página de inicio personalizada
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: '0644'

- name: Iniciar el servicio de apache
  service:
    name: httpd
    state: started
    enabled: yes
