apiVersion: v1
kind: Pod
metadata:
  name: debugger
spec:
  containers:
  - name: debugger
    image: lachlanevenson/k8s-kubectl:latest
    command: [ "/bin/sh" ]
    args: [ "-c", "sleep infinity" ]
    stdin: true
    tty: true
