apiVersion: v1
kind: Pod
metadata:
  name: nginx-mariadb-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: mariadb-container
    image: mariadb:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: yourpassword
    ports:
    - containerPort: 3306
