---
- name: Instalar Httpd
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Copiar página de inicio personalizada
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: '0644'

- name: Iniciar el servicio de apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: Deploy script.js
  template:
    src: script.js.j2
    dest: /var/www/html/script.js
    owner: apache
    group: apache
    mode: '0644'

- name: Deploy style.css
  copy:
    src: style.css
    dest: /var/www/html/style.css
    owner: apache
    group: apache
    mode: '0644'
