---
- name: Install dependencies
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pyhon_packages }}"

- name: Install Flask and MySQL connector
  pip:
    name: "{{ item }}"
  loop: "{{ pip_packages }}"

- name: Find the process using port 5000
  shell: "lsof -t -i :5000"
  register: pid_on_port
  ignore_errors: yes

- name: Kill the process using port 5000
  shell: "kill -9 {{ pid_on_port.stdout }}"
  when: pid_on_port.stdout != ""
  ignore_errors: yes

- name: Deploy API application
  template:
    src: app.py.j2
    dest: /home/ec2-user/app.py
    mode: 0755

- name: Start API application
  command: nohup python3 /home/ec2-user/app.py &